### ISSUE TITLE
Rename this app to CssVariablesManager

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/CssVariablesManager#12]
Rename this app to CssVariablesManager. This will be more accurate.

Comments?

cc @tomalec, @PatrykSzwer, @mmnosek

**Comment by PatrykSzwer** [comment]
Definitely good idea. 👍

**Comment by tomalec** [comment]
agree

**Comment by warpech** [comment]
@Mihaiii could you pls rename everything in this repo what is now called "CssThemer" to "CssVariablesManager"?

**Comment by Mihaiii** [comment]
Who can review PR #14 ?

**Comment by warpech** [comment]
Thanks, I will review.

**Comment by warpech** [comment]
Closing as done.

@Mihaiii pls close fixed issues when finishing a PR. Thanks!
