### ISSUE TITLE
Replace the term "theme"

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/CssVariablesManager#15]
After https://github.com/StarcounterApps/CssVariablesManager/issues/12, this app is now called **CssVariablesManager**, but it still uses a very ambiguous term *theme*. I propose to change it to *collection*.

After this change, README.md would look like:

> # CSS Variables Manager
> App used as a frontend to manage values of CSS variables. For easier workflow, the variables are grouped in collections.
> ## Collection
> A collection of CSS variables can be given a name. 
> 
> You can refer to the collection using a URL. To render the collection in actual CSS, pin the render URI `/CssVariablesManager/rendered-themes/{collection ObjectId}` anywhere in your view.

@tomalec, @miyconst, @PatrykSzwer, @Mihaiii - any better ideas than "collection"?

**Comment by tomalec** [comment]
so "the collection" is nothing more specific that just "a collection of CSS variables"?

If so, I think it's fine.

But we need to keep in mind not to make it "The Collection" (with Starcounter-specific meaning) as we did with "partial" and we are still tend to do with "composition"

**Comment by warpech** [comment]
It's just "a collection of CSS variables". Other name would be "a group of CSS variables", but I think that "collection" is better.

The purpose of it is to easily create color schemes, etc.

**Comment by Mihaiii** [comment]
> You can refer to the collection using a URL. To render the collection in actual CSS, pin the render URI /CssVariablesManager/rendered-themes/{collection ObjectId} anywhere in your view.

So for URIs I should make the change (from "/CssVariablesManager/rendered-**themes**/{collection ObjectId}" to"/CssVariablesManager/rendered-**collections**/{collection ObjectId}" ) ?

**Comment by Mihaiii** [comment]
Closing as done.
