### ISSUE TITLE
Wrong deleted row

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/CssVariablesManager#25]
While working on a task for Barcodes, I noticed a bug so I looked up in the code.
Because I couldn't find anything wrong within Barcodes' code, I tried to reproduce it in Content app (I reproduced it) and in CssVariablesManager (also reproduced it).
After that I downgraded Starcounter version to **2.3.1.6826** and with that version the behavior is normal (**no bug**).

Please see the gif. 

Reproduce:
Add multiple rows, delete first (for example) row - everything is ok.
Delete what is now the first row (without refreshing the page) and it deletes the 2nd one.
You can keep doing this unil nothing happens when you try to delete the last remaining row.

![bug](https://user-images.githubusercontent.com/8951553/28741142-849e75cc-7410-11e7-9f43-1850a734bea9.gif)

**Comment by warpech** [comment]
It definitely looks like a regression. Last version of Starcounter that works good is 2.3.1.6841 (Jul 20, 2017 4:09:02 AM), first version that works bad is 2.3.1.6846 (Jul 21, 2017 1:17:09 PM).

[The commits on Jul 20th](https://github.com/Starcounter/level1/commits/v2.3) suggest that this is caused by switching from PuppetJs 2.5.x to Palindrom 3.0.0. 

@alshakero could you pls check that?

**Comment by alshakero** [comment]
You can close this, it is tracked in https://github.com/Palindrom/JSONPatcherProxy/issues/9.

**Comment by alshakero** [comment]
@warpech thank you so much for isolating the version.

**Comment by Mihaiii** [comment]
Closed as another issue was created.

**Comment by alshakero** [comment]
Hi @Mihaiii! Could you please download the new RC (2.3.1.6971) and check whether this is fixed?

**Comment by Mihaiii** [comment]
@alshakero It's partially solved. The deleted row is the correct one, but nothing happens when I try to delete the last remaining row.
I tested it in CssVariablesManager and Barcodes also, just to be sure.

If you want to try it, just follow the steps in the gif (add 3 or 4 rows) and start deleting the first row. When you click "delete" on the last one, nothing happens (but, like I said, the deleted rows are the correct ones).

**Comment by Mihaiii** [comment]
> I tested it in CssVariablesManager and Barcodes also, just to be sure.
Just tested it in Content app also and it's the same behavior.

**Comment by alshakero** [comment]
I **guess**, the last item issue is totally unrelated to this. Will investigate ASAP.

**Comment by Mihaiii** [comment]
I had a look at the code hoping that if I try to debug this, when the solution comes out, I'll be able to understand better the code (big props for it, btw). 
I noticed what is in this pic. Is it normal?

<img width="939" alt="huhjs" src="https://user-images.githubusercontent.com/8951553/29231758-aa33d77c-7ee8-11e7-858d-d151643a8c6e.png">
