### ISSUE TITLE
Delete button not working.

### ISSUE THREAD

**Issue by PatrykSzwer** [StarcounterApps/CssVariablesManager#9]
### Steps to reproduce
1. Go to /CssThemer/themes
2. Add new theme.
3. Click Delete button on newly created theme.
### Expected result
Theme should be deleted.
### Actual result
Nothing happen.

##### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge

**Comment by Mihaiii** [comment]
Who can review?

**Comment by PatrykSzwer** [comment]
@warpech should I review this or You will do it?

**Comment by Mihaiii** [comment]
Closing as fixed.
